image: apacph/sphinx-plantuml:latest

stages:
  - build

pages:
  stage: build
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt -U
    - sphinx-build -b html ./docs public
  artifacts:
    paths:
      - public
  tags:
    - docker
  only:
    - main
